### PR TITLE
Hassio Addon

### PR DESCRIPTION
**Pull request by youseeus**
This is work in progress. But i don't know if I'll find time in the next weeks for further improvements so here is the state of my shot to bring this in as add-on into Home Assistant:

- you can install it as local plug-in (see README)
- you can enter your credentials on the add-on options-page
- the api-token survives a reboot of the add-on
- a small web-ui to guide the user (needs improvement)

what's missing or would be nice:
- automatic exposition of the sensor 
- HACS config

### CODE REVIEW

**Comment by Dielee** [comment]
First, this is a good idea! But, I don't use Hassio, so I can't test it. 
I am open to this change, however the code as well as the readme must still work for standalone operation.
Feel free to develop into this PR. I will test the changes if you'r done. You have to test the hassio part.

**Comment by youseeus** [comment]
i have fixed the docker and local workflow

**Comment by jturnbull** [comment]
I just installed this on Home Assistant and it worked great. Using the SSH addon I cloned youseeus's branch directly into the addon directory and then did the local install as per the HA docs.

The install process takes a very long time, with no feedback, but that's a HA issue.

Thanks!

**Comment by Dielee** [comment]
Thanks for feedback!
I will merge this feature, if this works well!

@youseeus is your work done ?

**Comment by youseeus** [comment]
there are some things to do (like documentation, beautification etc) but the feature is working fine for me 5 months. So i would close this PR.

**Comment by youseeus** [comment]
It would be nice to install it via HACS on homeassistant (so you don't have to use SSH) but i don't know anything about that.

**Comment by youseeus** [comment]
i've restructured the whole project no on my fork so it can be used as AddOnRepository. i don't know if you want that in yours? it's still in Progress... but you can take a look into it

**Comment by Dielee** [comment]
Yeah, really nice! Feel free to submit a PR.

**Pull request closed without merging**
